title: Edward Heyne Blog
description: 

url: http://eheyne.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: eheyne
   twitter: eheyne
   facebook: eheyne
   email: edwardheyne@gmail.com

google_analytics: "UA-58263416-1"
